version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies"
      - yum update -y
      - yum install -y maven aws-cli
      - mvn install -DskipTests

  pre_build:
    commands:
      - echo "Running pre-build tasks"
      - mvn clean

  build:
    commands:
      - echo "Building the application"
      - mvn package -DskipTests

  post_build:
    commands:
      - echo "Build completed successfully"
      - echo "Getting the JAR from S3"
      - aws s3 cp s3://staticpro-dest/demo-for-deploy-the-springboot-0.0.1-SNAPSHOT.jar /home/ec2-user/demo-for-deploy-the-springboot-0.0.1-SNAPSHOT.jar
      - echo "Downloading the PEM file from S3"
      - aws s3 cp s3://staticpro-dest/cloud27.pem /tmp/cloud27.pem
      - chmod 400 /tmp/cloud27.pem
      - echo "Running the JAR file on EC2"
      - ssh -o StrictHostKeyChecking=no -i /tmp/cloud27.pem ec2-user@13-60-202-115 "java -jar /home/ec2-user/demo-for-deploy-the-springboot-0.0.1-SNAPSHOT.jar"

artifacts:
  files:
    - target/*.jar
  discard-paths: yes
